### ISSUE TITLE
攻撃の選択

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#10]
https://github.com/at0x0ft/SRPG2018/blob/790c41a5a536e29e84fa960a76e1e55fc7b50be3/Assets/Scripts/MoveController.cs#L113-L129

上記の119行目について
移動完了後に, ユニットの持っている攻撃を(セット数に応じて)展開し, 攻撃選択ウィンドウ, 及び, 攻撃自体の詳細を説明したウィンドウを画面に表示し, 攻撃を選択した際に攻撃範囲をハイライトするようにしたい.(詳細要議論)

**Comment by at0x0ft** [comment]
#13 とも関連して, 攻撃を選択するサブウィンドウとの兼ね合いを考えて, UI周りを担当している僕がそのまま引き受けます.

**Comment by 25toma** [comment]
何故か#22がこっちにmergeされちゃってますが手違いです（戻し方わかんないので放置します・・・）
