### ISSUE TITLE
[bug] ゲームが終わらない

### ISSUE THREAD

**Issue by kumachan-mis** [at0x0ft/SRPG2018#100]
みすちゃんの体力が0になって敗北しても, WINだのLOSEだのが出ない.

水星ちゃんはもう死んだはずのしかばねに攻撃を仕掛けるのである. 
それどころではない. 今度はプレイヤーが水星ちゃんを自由に行動させられるのである.
負けるとなぜか加勢する敵キャラクター. しかしそこには何もいない.
ただ石ころと木と草むらが広がるばかりである.

その謎を解明するために我々はアマゾンの奥地へと足を進めた.

**Comment by at0x0ft** [comment]
実はゲームが終了しないのは,  __†　仕　様　で　す　†__
UnityはApplication.Quit()を見つけても, エディタ上でのテストプレイ時にはそのままスルーする模様.
(実際にビルドしてちゃんと終了することは確認しました).
ですが戦闘終了時の挙動がないのは寂しいので時間が許す限り作ります.
