### ISSUE TITLE
強攻撃が分かりにくい

### ISSUE THREAD

**Issue by Kabierror** [at0x0ft/SRPG2018#102]
強攻撃が強攻撃であることを判別しにくい。
弱・中・強の分類を技詳細に載せたり、種類ごとに技名の色を変えたりした方が良さそう？

**Comment by kumachan-mis** [comment]
ついでに言うと, 攻撃を受けると強攻撃のチャージがキャンセルされることにしばらく気づかなかったので, そこもわかるようにした方が良さそう

**Comment by 25toma** [comment]
強攻撃の雰囲気はChargeEffect.cs?により、サイヤー人のようなオーラを背後に発生させることで実装出来ました。
また、攻撃チャージのキャンセルも、オーラの削除で見えるようになりました。
クローズしたいです。
