### ISSUE TITLE
強攻撃の溜めと, 溜め解除の実装

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#11]
強攻撃の溜めと, 相手から攻撃された際に溜めの解除を行う. この仕様を実装してほしい.
具体的には, 強攻撃の溜め状態を表すメンバ(プロパティ)を実装(Enum型?)し, 上記に示したような処理を, 当該クラスに対して行う.(詳細要議論)

**Comment by at0x0ft** [comment]
強攻撃溜めフラグ (Enum型)については、 #20 のStatusプロパティを使用するものとする.

**Comment by at0x0ft** [comment]
強攻撃についての仕様抜粋

* 強攻撃は1セット目でのみ発動可能
* 強攻撃使用後、キャラクターは溜め状態に入り、そのまま行動を終了する
* 強攻撃溜め状態で攻撃された場合、強攻撃溜め状態が解除され、その後の2セット目では(中)攻撃はできない. なお、移動は可能とする.
* 操作キャラの行動順になった際に、強攻撃溜め状態かつ2セット目である場合、移動はできずに強攻撃を発動する.

足りない仕様があった場合には指摘お願いします.

**Comment by 25toma** [comment]
#5 が終わるまで、ここら辺詰めてるね～

**Comment by 25toma** [comment]
状態遷移はこういう感じ？
![implement3](https://user-images.githubusercontent.com/22388369/47257443-cba5f980-d4c8-11e8-9676-d813037607c5.png)

**Comment by 25toma** [comment]
攻撃コマンド選択時にSetの情報が不要な手法が見つかったので、
簡略化する場合はこちらを実装します。
ざっくり言えば、#20 にてAttackableをLittleAttack/MiddleAttackに分割することで、
Attackableが事実上のSet1,その他がSet2を表す手法です。

全体図(アクティビティ図で表現)
![default](https://user-images.githubusercontent.com/22388369/47258384-74f2ec80-d4d5-11e8-97e0-681ed44d6839.png)

状態遷移図(アクティビティ図で表現)
![default](https://user-images.githubusercontent.com/22388369/47258387-78867380-d4d5-11e8-812c-e6ddb024be12.png)

**Comment by 25toma** [comment]
3日放置したけど特に問題点指摘されてないので、これ今後実装していきます。

**Comment by 25toma** [comment]
この内容は、#22 の一部となりました。
