### ISSUE TITLE
ヒント画面の作成

### ISSUE THREAD

**Issue by 25toma** [at0x0ft/SRPG2018#110]
現状では、解説PDFを元にプレイヤーがするべきことを探して遊んでいる。
それの頻度を減らすために、画面下方の方に新しくウィンドウを作り、
何をするべきなのかが分かるようにしたい。

細かい予想仕様は以下の通り
- チェックボックスを隣に配置し、ONの時にのみ表示する
- 青背景は無しで、黒背景に白文字を浮かび上がらせる（青色成分が多すぎるので）
- (未定)外部からは、MessageBoxを活用して動作させていく?

**Comment by at0x0ft** [comment]
"戦況確認フェーズ":「マス・ユニットをタップして戦況を確認してください」
"移動フェーズ":「移動先をタップしてください」
"攻撃フェーズ"(1・2サイクル目):「攻撃を選択し, 攻撃対象をタップまたはチャージボタンを押してください」
"攻撃フェーズ"(2サイクル目、溜め攻撃発動時):「攻撃対象をタップまたは範囲攻撃ボタンを押してください」
(相手ターン:「相手のターンです、終わるまでお待ちください」)

**Comment by at0x0ft** [comment]
こんな感じかな?

**Comment by 25toma** [comment]
b
後、配置は画面下部の空白で良いかな？
(enemy speed設定の左側)

**Comment by at0x0ft** [comment]
おkです
