### ISSUE TITLE
各キャラの顔アイコンとHPバーの画面上部への表示

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#130]
画面上部に、各キャラの顔アイコンとHPバーを表示し, 左側や右側に現在行動中のユニットをActiveIconと同様に, 指すようにする.

**Comment by at0x0ft** [comment]
嘘, ごめんなさい.
既に終わってましたのでNovelやっていただけると良いかなぁって感じです.

**Comment by 25toma** [comment]
別issueで実装したためクローズ
