### ISSUE TITLE
移動可能範囲に消費コストを印字する

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#133]
具体的にどのくらいコストが必要なのかが分かりにくいというフィードバックを受けて.
実装自体はさほど難しくないと思われる.

**Comment by 25toma** [comment]
assignee を isoyaにしてもらいたい気分
（move controller周りをやっているから、多分一番敷居が低い）。

後、(恐らく?)機能面が似ているスクリプトはActiveUnitIcon, HPBar辺りだと思うので、
詰まったらその辺りからコピペとか出来そう。

**Comment by at0x0ft** [comment]
なるほど.
ほんならそうさせていただきます.

**Comment by 25toma** [comment]
とりあえずは、各Floorの子オブジェクトにTextオブジェクトの配置及び、
そのオブジェクトの描画する数値の見た目の調整を行います。
