### ISSUE TITLE
ノベルシーンの基盤を作成

### ISSUE THREAD

**Issue by 25toma** [at0x0ft/SRPG2018#140]
とりあえずノベルシーンの基本的なところを作ります。
細かい機能については、その都度issueを作っていきます。
以下のサイトを使っていく予定です。
https://coffee-ryo.hatenablog.com/entry/2018/07/11/224312

**Comment by at0x0ft** [comment]
問題ないです. 無料アセットガンガン使ってください.

**Comment by 25toma** [comment]
note:
Novelは二次配布が出来るか分からないため、gitには上げません。
Novelを動作させる場合は、FungusをAssetStoreからDownloadし、
Assets直下に保存してください。

**Comment by 25toma** [comment]
ノベルのイメージとしては、
キャラクタデータはprefab化し、それらを各chapterにEditor上で取り込んで使用するようにしています。
シナリオデータと立ち絵動作情報については、Editor上にシナリオをコピペしたり動作を定義させてシーンファイルを保存/共有するようにしています。
