### ISSUE TITLE
chapter1-2debug

### ISSUE THREAD

**Issue by 25toma** [at0x0ft/SRPG2018#147]
chapter1-2がmergeされるときに、立ち絵の消滅などがあったので、それを修正します。

**Comment by at0x0ft** [comment]
あ、それと、Chapter1と2のBattleScene、Floor系のScript書き換えたせいで正常に動かなくなっている(Floorの種類が正常にセットされていない)ので、GameObject>Create by Scriptから新たに床のランダム生成して、UnitのスクリプトのInspectorのInitialFloorの再設定とかしておいて貰えるとありがたいです.

**Comment by 25toma** [comment]
何か、全てのFloorがunmovableになってるんだけど・・・

**Comment by at0x0ft** [comment]
そうそう、だから、↑2で書いたようにGameObject>Create by Scriptを選んで
それぞれのFloorの比率テキトーに設定してランダムで床生成しなおして

**Comment by 25toma** [comment]
エフェクトバグ治った！
mergeはお好きなタイミングで…（別の重いタスクもあるから、すぐには次には移れない）

**Comment by at0x0ft** [comment]
Unity入ってるパソコン開いたからサクッとmergeしちまいます.
