### ISSUE TITLE
AIバグフィックス

### ISSUE THREAD

**Issue by 25toma** [at0x0ft/SRPG2018#175]
攻撃出来るのにしないので、原因探ります

**Comment by 25toma** [comment]
原因が判明したので投げておきます。
移動モーションの実装を見ると移動完了時にCoordinatePairに移動後の座標が代入されているのですが、
これにより移動完了しなくては移動後座標が取得できなくなっています。
そのため動作のシリアライズ化（移動モーション中は攻撃フェーズに移行しない）という制約を追加して対応していきます。

多分これで、攻撃出来るのに攻撃しない敵も何とかなるはずです。

**Comment by 25toma** [comment]
AI側の制御を高レイヤから丸め込んで無理やり解決できました

**Comment by at0x0ft** [comment]
お疲れ様です･･･
プルリクオナシャス

**Comment by 25toma** [comment]
盤面規模の測定ミスによる安地バグを見つけたから直してたら、
何かプレイヤー視認範囲の不整合による配列外参照バグが見つかって修正中。

**Comment by 25toma** [comment]
は？何もしてないのにバグが発生しなくなった。キレた。

後また別のバグが発生して更にキレた
