### ISSUE TITLE
現在のバトル盤面の状態を表すプロパティの追加

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#19]
Subset of #5 
BoardControllerクラスに, 現在の盤面の状態を表すEnum型プロパティ, Stateを追加してほしい.
(#5 を実装する上で必要)
具体的には, 
* CheckingStatus (戦況確認中)
* Move (移動コマンド入力中)
* Attack (攻撃コマンド選択中)
* Loading (スクリプトサイドが処理中)
の4状態を持つ.

この4状態以外が必要, 或いは各状態の名前が変である等の指摘がある場合には, コメントください.

**Comment by 25toma** [comment]
追加で
- target (攻撃対象/方向選択中)
が欲しいです。

後、攻撃モーションなどはありますか？それによってもう1つ必要そうですが。

**Comment by at0x0ft** [comment]
うーん、targetの用途はどんなところで必要そう?
攻撃モーションは正直微妙なところです (多少左右に動かしてエフェクト出して終わりになりそう).

**Comment by 25toma** [comment]
あ、targetが無くても、Unitの選択しているrangeによって、攻撃コマンド選択時と攻撃範囲選択時の区別が可能かな？

**Comment by 25toma** [comment]
ふと、UIのレベルで考えると、現在状態を表す変数があると挙動が楽な気がしたんですけど、どうでしょう。対して必要じゃないですかね？

**Comment by at0x0ft** [comment]
いや、楽ではあるはずです.
ただ、攻撃/移動範囲表示ってのはUIから独立しているため、targetはなくても大丈夫かなぁなんて思っていた次第です.

**Comment by 25toma** [comment]
では無しで行ってみます。マージしても良いですか？
