### ISSUE TITLE
ユニットをクリックした時に移動可能なマスがハイライトされない

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#2]
恐らく原因はMoveControllerクラス内のGetRemainingMoveAmountInfos()メソッド内.
アルゴリズムか何かが間違っている関係で, 直後の戻り値のDictionaryの長さを返しても1しか返ってこない.
中のアルゴリズムの妥当性を検証してほしい.

**Comment by 25toma** [comment]
本日中は、アルゴリズム検証してみます。
無理そうだったら誰かにぶん投げます。

**Comment by 25toma** [comment]
reason may be detected.
_initialFloor.CoordinatePairを元にunitの初期位置を決めるが、
そもそもその値が、設定されていない。

**Comment by 25toma** [comment]
上記のバグは、あたふたの環境では再現できないバグの可能性あり。
無理やり実行順序を変える手法をとって、localで新規のバグをつぶしました。
元々のバグは未だ健在です。

**Comment by 25toma** [comment]
当初のバグの原因を発見しました。
Unitスクリプトでは、MaxMoveAmoutとMoveAmountがあるのですが、
Turn開始時に、MoveAmountの値が更新されていません。

**Comment by 25toma** [comment]
bugfix後、新たにエラーがあるため究明します

**Comment by at0x0ft** [comment]
ありがとうございます.
こちらも後で検証します.

**Comment by 25toma** [comment]
現在のバグの原因が凡そ分かったので、それに関するサイトを置いておきます。
http://www.atmarkit.co.jp/fdotnet/dotnettips/952firstordefault/firstordefault.html

要約すると、List.First(~~)を使うと、1つも要素が見つからないときに例外を吐くため、別の関数を使いましょうということです。

**Comment by 25toma** [comment]
もう1つ、移動経路でバグがありましたので、修正してます。

要約すると、MoveController.RevTraceRouteの返り値で、昇順と降順が間違えていたという感じです。

**Comment by at0x0ft** [comment]
Really Thank you very much!
圧倒的感謝, ありがとうございました！
close #2

**Comment by at0x0ft** [comment]
ブランチマージしてしまいます
