### ISSUE TITLE
移動/攻撃/戦況確認の仕様の明確化と, それに伴うユニット/マスのタップ時動作の正確な実装

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#22]
詳細は後ほど書く.
具体的には #19 に関連して, UnitクラスやFloorクラスのOnClickメソッドの中身の動作を整理する.

**Comment by 25toma** [comment]
#11 はどう考えても、バトルの進行順序的にデバッグが難しいです。
そこでとりあえずbranchだけ残して、masterから新しくこちらのbranchを作成します。

**Comment by 25toma** [comment]
あたふたが詳細を書く時間を割けるタイミングがいつ来るか分からないので、こちらでUMLを少しずつ書いていきます。

**Comment by 25toma** [comment]
![onclick](https://user-images.githubusercontent.com/22388369/47385862-25ffbe00-d746-11e8-8dc4-551500d790c3.png)

ユニット,マスなど、バトル画面においてUnityEditorから存在が予測できるクリック時動作、
その全てに対する、凡その動作フローの提案書がこれです。
ところどころ分からない部分は、黒枠で囲んで書いてあります。

**Comment by at0x0ft** [comment]
戦況確認 -> 移動への遷移は, 手番ユニットのダブルタップで良いかなぁって思いました.
そのためには手番ユニットがどのユニットであるかをBoardControllerあたりで持っておく必要があるので, 至急 #28 に取り掛かって提示します.

**Comment by at0x0ft** [comment]
単体攻撃の際に, 敵のいない場所に関しては空振りってことにします (ってかそういう感じでRangeAttackを変えてしまったので).

**Comment by at0x0ft** [comment]
手番のユニットをタップする毎に
戦況確認 (初期状態) -> 移動 -> 攻撃
と遷移することとし, 攻撃状態の場合に攻撃選択ウィンドウが生成され, そこから可能な攻撃を選ぶことでマップがハイライトされ, 攻撃範囲を絞っていく (場合によっては, #5 で提示されたUIを新たに生成する) という方向で進めたいと思っています. (仕様にしたい)

**Comment by at0x0ft** [comment]
キャンセルは実装がダルすぎるので取り敢えず保留, 後でまた考えるということにしましょう.

**Comment by at0x0ft** [comment]
先述の通り, 取り敢えず #28 に取り掛かります.

**Comment by 25toma** [comment]
FocusingUnitとActiveUnitがありますが、
この差は、

- FocusingUnit : さっきクリックしたユニットの情報
- ActiveUnit : 現在攻撃出来るユニットの情報

という感じで良いですか？

**Comment by 25toma** [comment]
既知の問題：

- ActiveUnit以外がButton.Interactive=falseとなっているため、UnitInfoWindowのためのクリック検知が出来ない。

**Comment by 25toma** [comment]
要望：

- FocusingUnitをnullにするだけの関数が、_unitsに欲しい。

**Comment by at0x0ft** [comment]
<FocusingUnitとActiveUnitの違い>
そうです.

BoardController.NextUnit()使うためにBoardControllerインスタンス持っても(追加しても)良いです.
そこは後でテキトーにこっちで対処します.

**Comment by at0x0ft** [comment]
ActiveUnitに対してタップを繰り返すことで, 
戦況確認モード (他のユニットも確認できる) -> 移動モード (移動可能範囲ハイライト) -> 攻撃モード (攻撃選択ウィンドウ生成 -> 攻撃可能範囲ハイライト) -> 戦況確認モード･･･
って感じで切り替わるのを想定していて, 各モードからEndCommandButton

**Comment by at0x0ft** [comment]
これだとなんかコーナーケース出そう･･･?

**Comment by 25toma** [comment]
（流れとは別で書きたいやつ）
TODO（issue22に明示されてない内容）

- FocusingUnitをnullにするだけの関数(in units)
- BoardControllerインスタンス追加(in map)
- func NextUnit(in map)
- 弱攻撃,中攻撃,強攻撃を区別するenum追加(in Attack)

issue分けた方が良いとかあれば教えてください。

**Comment by at0x0ft** [comment]
あー本当だ, 弱中強を区別するEnumがないわ

**Comment by at0x0ft** [comment]
取り敢えず, BoardControllerインスタンス追加(in map)と弱 中 強攻撃を区別するEnum型追加を別issueで立てて俺が今実装でよろしい?

**Comment by 25toma** [comment]
ActiveUnitタップの件：

1.EndCommandButtonが、唯一のモード遷移条件？（ハイライトを何度も押せる）
 それとも、ハイライトの場所をクリックしたら強制モード遷移？
2.攻撃コマンドで、詳細表示する気がUI見てたらしたけど、それの発生条件は？

**Comment by 25toma** [comment]
BoardController追加, Enum追加をしてもらえるのであれば、それをmasterにmergeしてくれれば後で僕がpull&mergeします

**Comment by at0x0ft** [comment]
1.
ハイライトの場所をクリックしたら強制モード遷移です.
2.
攻撃モードになる -> 攻撃選択ウィンドウを生成 -> ユーザに攻撃を選ばせる -> 攻撃の詳細ウィンドウを右側に更に追加で(攻撃選択ウィンドウを左に開いたまま)展開 & 選択された攻撃の範囲をハイライト
って感じで考えてます.

**Comment by at0x0ft** [comment]
↑2
引き受けてすぐにpushします.

**Comment by 25toma** [comment]
攻撃選択ウィンドウでは、何度も色んな種類をクリックしてOKってことで良いよね？（念のため）（AttackControllerレベルでの実装は容易です）

**Comment by at0x0ft** [comment]
おkです

**Comment by at0x0ft** [comment]
ブランチ22-1に二つ実装しときました. マージしてお使いください

**Comment by 25toma** [comment]
> ActiveUnitに対してタップを繰り返すことで,
> 戦況確認モード (他のユニットも確認できる) -> 移動モード (移動可能範囲ハイライト) -> 攻撃モード (攻撃選択ウィンドウ生成 -> 攻撃可能範囲ハイライト) -> 戦況確認モード･･･
> って感じで切り替わるのを想定していて, 各モードからEndCommandButtonを押すことで, 行動を終了することができる, という仕様を想定しているので, それを考えております.

勘違いしてた気がするので確認だけど、もしかして行動を終了＝次のユニットに移る
という感じかな

**Comment by 25toma** [comment]
BattleState.Loadingが示す状況は、とりあえず攻撃アニメーションのみを想定します。
他に発生した場合は教えてください。
