### ISSUE TITLE
Sceneの結合と画面拡大やBGM等新たに追加された機能の各BattleSceneへの追加

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#222]
タイトル通り.
after merged master <- #98 .

**Comment by 25toma** [comment]
他のbranchは全部battle系ではないため、一気に変えます

**Comment by at0x0ft** [comment]
ゐ

**Comment by 25toma** [comment]
メモ：

- effectの内部削除をシーン以降時に出来ていないため、DOTWEENが警告を出す（操作問題なしのため先送り）

**Comment by 25toma** [comment]
ErrorWindowの挙動が少し変わりました

**Comment by 25toma** [comment]
Chapter5でAI関連のバグが見つかったので後で直します。

**Comment by diversityisoya** [comment]
新機能の動作は問題ないと思います。
あと、ごめんなさい。
Chapter3のdarkmoonとlightmoonの
Raycast Targetがoffになってました。

**Comment by 25toma** [comment]
raycastは後で直してください

**Comment by 25toma** [comment]
全シーンに適用終わりました。

**Comment by 25toma** [comment]
> 新機能の動作は問題ないと思います。
> あと、ごめんなさい。
> Chapter3のdarkmoonとlightmoonの
> Raycast Targetがoffになってました。

直しといた

**Comment by at0x0ft** [comment]
masterにmergeしました
