### ISSUE TITLE
Floorの名前が意図しないものであるときに警告を表示する

### ISSUE THREAD

**Issue by kumachan-mis** [at0x0ft/SRPG2018#3]
各Floorのunity上での座標と盤面のマス目としての座標の間での変換を行うために, マス目上で座標(x, y)にあるFloorの名前は
`(x, y)`
の形式をしている必要がある.

https://github.com/at0x0ft/SRPG2018/blob/790c41a5a536e29e84fa960a76e1e55fc7b50be3/Assets/Scripts/Editor/CreateFloors.cs#L95
https://github.com/at0x0ft/SRPG2018/blob/790c41a5a536e29e84fa960a76e1e55fc7b50be3/Assets/Scripts/Floor.cs#L120-L124

しかしながら, ゲームオブジェクトの名前は自由に変更できてしまうため, 意図しない名前にすることもできてしまう.

Floorの名前が意図しないものであるときには, デバッグログに警告を表示して, ゲームの実行を終了するようにしたい.

意図しないフロアの名前とは, 例えば次が想定される：
* そもそも`(x, y)`の形式に沿っていないものがある.
* ゲーム盤面が高さH, 幅Wであるとき, (0, 0)-(W-1, H-1)のうち不足しているもの, あるいは余計なものがある.

**Comment by 25toma** [comment]
Floorの名前を検査するタイミングをどうするかで、状況は変わりそう。
今思い付く案は2~3個。
1. ゲーム開始時にのみ検査（実行オーバーヘッド小, 安全性小）
2. セット更新など,一定の動作毎に検査（実行オーバーヘッド中, 安全性中）
(3. さらに細かく？)

**Comment by kumachan-mis** [comment]
このissueは開発者が作業をしやすくするためのものなので, ゲーム開始時だけで十分だと思う.
ゲームオブジェクトの名前をプレイヤーが変更することはないはず.

**Comment by at0x0ft** [comment]
RectTransformを上手い事弄ることで, 現状の名前から座標を取得するような手法を打開できる可能性が出てきたため, issueをReopenとしました.
新たなissue等を立てた方が良い場合, また追加でご指摘ください.
