### ISSUE TITLE
属性の強弱関係の設定に過不足があるとき警告を表示する

### ISSUE THREAD

**Issue by kumachan-mis** [at0x0ft/SRPG2018#4]
インスペクタでの属性間での強弱設定は, 各属性に対して
```
強い：　　属性A,属性B, ...
やや強い：属性C
普通：　　属性D
やや弱い：(なし)
弱い：　　属性E, 属性F
```
のように, それぞれ該当するところに列挙する形で行なっている.

https://github.com/at0x0ft/SRPG2018/blob/790c41a5a536e29e84fa960a76e1e55fc7b50be3/Assets/Scripts/Type.cs#L9-L16

この設定方法では, 複数の欄に1つの属性を含めたり, どこにも含まれない属性があったりする設定が可能となっている.

そこで, この強弱関係の設定方式は変えることはしないで, 属性の強弱関係の設定に過不足があるときには, デバッグログに警告を表示して,  ゲームの実行を終了するようにしたい. 警告には, 次のことが含まれているのが望ましいと思う：
* 不足があるとき, どの属性の強弱関係が未設定であるかの一覧
* 重複があるとき, どの属性がどの欄に重複して存在しているかの一覧

追記 : ユーザーからの意図しない入力への対処ではないので, 検証は起動時の最初の1回だけでいいです.

**Comment by 25toma** [comment]
私としては、イソノにAssignしたいのですがどうでしょう。

**Comment by at0x0ft** [comment]
isoyaにAssignし, #3 と#4 を優先的に片づけてもらうことにしたいと思ってます.

**Comment by diversityisoya** [comment]
Type.csは全種類のタイプを把握してないのに、強弱設定の過不足チェックはできるのでしょうか。
(属性リスト作ってもいいけど)
実装はType.csにInitilize()作ればいいのかな。

**Comment by kumachan-mis** [comment]
属性リストを何らかの方法で得て, initializeでチェックでいいと思う
