### ISSUE TITLE
長距離ユニットによる範囲攻撃の、一連の関数のコーディング

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#5]
https://hackmd.io/Zm_TNPfFRCK1a5zs7EHgZw#
の1.4 - 3より, 攻撃には範囲攻撃と単体攻撃の2種類が存在する.
単体攻撃は従来のメソッドで完了しているが, 範囲攻撃に関しては, 一切実装されていない.
そこで, 
1. Attackクラスに攻撃種類[単体/範囲]の区別するEnum型メンバ(プロパティ)を新たに追加

し, 

2. Enum型プロパティで攻撃メソッドの呼び出しを切り替え,
3. 範囲攻撃の場合の攻撃メソッドを実装

の3種類の実装をしてほしい.

メンバ名/メソッド名等はMerge前等でこちらでもチェックするのであまり気にせずにテキトーに命名して進めてほしい.

**Comment by 25toma** [comment]
mergeをpullする前にbranchを作っちゃったらしいので、一度branch消して、再コミットします。

**Comment by 25toma** [comment]
マウスの位置を取得する処理を書いたスクリプト、mouse.csを後で作ります
（現在はAttackControllerに暫定的に埋め込まれてるやつです）。
さて質問ですが、マウスの座標の原点はどこにしますか？
左下で良いですか？

**Comment by 25toma** [comment]
範囲攻撃アルゴリズム：
0. 範囲攻撃を選択したとき、ハイライトを付け、攻撃方向を上に設定する。
1. マウスのクリックをtriggerとして、2に進む。
2. 範囲攻撃を選択中かつ方角を選択している場面で、3に進む
3. マウスクリック位置の、攻撃Unitに対する相対方角を取得する。
4. [if 現在予定している攻撃方角と同じ and 攻撃UnitのFloorではない]攻撃を開始する。
5. [else] 攻撃方角を変更する。

**Comment by at0x0ft** [comment]
先に #21 や, #19 の実装をした上で先に進めてください.

**Comment by 25toma** [comment]
[ワークフローの確認]
やることを明示化させておきたいため、書いておきます。
このissueでは、

- (呼び出すと)単体攻撃/範囲攻撃を判定して、ハイライト/攻撃の処理を分岐させる機能
- (呼び出すと)範囲攻撃用ハイライトを付けてくれる機能
- (呼び出すと)範囲攻撃を適用して次のターンに進む機能

を実装する予定です。これらの機能のために必要な実装として、 #19 , #21 のissueが存在します。
一方で、この機能よりも上位に位置する機能

- Floor,Unitをクリックしたときにおこる、ハイライトや攻撃のトリガー機能
- 攻撃範囲を選択する前に必要な攻撃コマンド選択機能

これらは(このissueでは)実装しない予定です。

**Comment by 25toma** [comment]
![implement](https://user-images.githubusercontent.com/22388369/47202635-b5107d00-d3b8-11e8-85e6-29b829a23e9d.png)

攻撃コマンド選択後～攻撃終了の範囲での、
実装レベルでの完成予定図です。
Ignoreが、このIssueで取り扱わない所です。

**Comment by kumachan-mis** [comment]
![2018-10-19 19 39 29](https://user-images.githubusercontent.com/29433058/47213652-9caf5b00-d3d6-11e8-9c57-24b135cfb2e1.png)
範囲攻撃のボタンはこんなものをイメージしている.

**Comment by 25toma** [comment]
TODO,
space→tab
function's contents

**Comment by 25toma** [comment]
主な実装は終わったため、#17 を用いてレビューの方をしてほしいです。
