### ISSUE TITLE
スクリプトのみGitで管理している関係上, Collabで同期してもアタッチしていたスクリプトに設定していたSerializeFieldが抜け落ちてしまう

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#50]
_<Gitで解決できる問題ではないが, 忘れやすい問題なのでここに書いておきます>_
タイトル通り.
回避策として挙げられるものは, Unity.packageみたいな形でUnityさえあれば.packageファイルを読み込んでプレイできる状態にする, など･･･

**Comment by at0x0ft** [comment]
それっぽい解決策見つけた
http://smartgames.hatenablog.com/entry/2016/03/15/223434

**Comment by 25toma** [comment]
幾つか情報を見つけたので張ります。

雑解説：
https://qiita.com/4_mio_11/items/91ebcdd30398af607373
http://tsubakit1.hateblo.jp/entry/20140613/1402670011

詳細解説：
http://madnesslabo.net/utage/?page_id=5640

**Comment by 25toma** [comment]
暫定でシンプルなのはこれかも：
http://www.keijiro.tokyo/unity-github-tutor/

正しいかは不明だけど、主原因はmetaファイルの混在。
僕が理解した範囲での、やるべきことは以下の通り

- 一度全てのbranchをmasterに統合する。
- 1名が、meta拡張子のファイルをgit管理にする。
- 所有する全てのmeta拡張子ファイルをmasterにmergeする。
- その後、そのmaster以前のものは使用しない

疑問点は、詳細解説読んでから考えてもらえると。

**Comment by 25toma** [comment]
想定している要因は以下の通り。
1. gitでmetaファイルを共有しないことにより、各コントリビュータ(以降:各員)の持つUnityが、初回起動時にmetaファイルを自動生成している。
2. 一方metaファイルには、ファイルの固有識別番号(通称:GUID)が記載されており、Unityはこれでファイルの存在判定を行っている。
3. 結果として、各員の持つスクリプトに割り振られたGUIDは異なる状況が発生し、ファイルが存在しないという状況に陥る。つまりはこのissueにおける設定のし直し。

なお、ここからはただの予想ですが、
コラボレートで管理しているものはUnity上でGUIDの統合はされていそうなので、あくまでscript限定な気がする。

**Comment by at0x0ft** [comment]
そもそもとしてこんなものがあった
http://kan-kikuchi.hatenablog.com/entry/GitHub_for_Unity

**Comment by at0x0ft** [comment]
(正式版とはいえ, diffが見られなかったりや, たまにUnityが落ちることがあるそうなのでやっぱ微妙か)

**Comment by kumachan-mis** [comment]
@at0x0ft このissueは問題なければクローズしちゃいましょう

**Comment by at0x0ft** [comment]
(一部ブランチのみであるとはいえ, )全てGitで管理する方向に変えたため, closeとします.
