### ISSUE TITLE
移動時にアニメーションをつけたい

### ISSUE THREAD

**Issue by diversityisoya** [at0x0ft/SRPG2018#57]
今経路情報をMoveController.csのrouteFloors[]に保存してある。
そこから現在の進行方向を算出して、
動かしているUnitのアニメーターをアタッチして
状態を変更させたい。
今回は2プレーヤーいるので、
スクリプトから動かすべきUnitの判別が必要となる。

**Comment by 25toma** [comment]
動かすべきUnitは、_units.ActiveUnitを参照して（現在動いてるUnitの情報がある）

**Comment by diversityisoya** [comment]
Sorting Layerを多少いじっても失敗。
Animatorに設定されているparameterはちゃんと変更されていることを確認した。
多分原因はImage(Script)がSpriteの上に表示されてアニメーションが見えないのではないか
っていう仮説に至った。でも別の環境だとSpriteの方が前に表示されるし、
あくまでも原則ってことかもしれない。

**Comment by 25toma** [comment]
Animationが無理そうなら、コルーチンという処理を検討してみて。
参考サイトは下の2つ。

- コルーチンの使い方( https://qiita.com/mo4_9/items/3aeac04b60531e314951 )
- script上での、Imageの書き換え方法( https://uni.gas.mixh.jp/unity/canvas-text-image.html )

sprite = Resources.Load<Sprite>("bag2")でspriteオブジェクトを取得するところを、
他のScriptみたいに[Serialized Field]付きの変数を作ってしまうのは必要。

**Comment by 25toma** [comment]
duplicate?
