### ISSUE TITLE
操作可能キャラクターを示す

### ISSUE THREAD

**Issue by Kabierror** [at0x0ft/SRPG2018#67]
現在行動できる(移動・攻撃が出来る)キャラクターの頭上にカーソルを表示すると良い。

**Comment by at0x0ft** [comment]
カーソルって他のFloorの押す場所が狭まったりして, 見にくくならない?

**Comment by at0x0ft** [comment]
現状では動かせるユニットを明るくしているからそれでも十分分かるというのはなくはない, とは思っている.

**Comment by Kabierror** [comment]
明るくなっていないキャラがクリックできない→ステータスの確認が出来ない
→他のキャラも明るくしたい→じゃあカーソル付けた方がよくない？
という流れ。

**Comment by Kabierror** [comment]
見にくくなるほど大きなものは必要ないかと。指し示されてるのが分かればよい

**Comment by at0x0ft** [comment]
なるほどな, じゃあステータス確認の時に他のユニットも明るくするように, 新たなissue立てないとな

**Comment by Kabierror** [comment]
そちらはくまちゃんが解決済み

**Comment by at0x0ft** [comment]
あ、そら良かった
