### ISSUE TITLE
プレイヤー交代時カットインの向上

### ISSUE THREAD

**Issue by at0x0ft** [at0x0ft/SRPG2018#88]
#65 に関連したタスク
ちょっと見栄えがよろしくないので, 画面全体を暗転 -> hogehoge 's order -> 暗転解除
と言う風に改善.

**Comment by 25toma** [comment]
http://tsubakit1.hateblo.jp/entry/2015/04/06/060608#%E3%82%B3%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%81%AE%E5%AE%8C%E4%BA%86%E3%82%92%E5%BE%85%E3%81%A1%E5%90%88%E3%82%8F%E3%81%9B%E3%82%8B

のうちの、コルーチンの完了を待ち合わせるという項がおススメ

**Comment by at0x0ft** [comment]
CutInPopUpクラス内, Move()でCoroutineを呼び出すとCoroutineがネストし過ぎてFadeの方のCoroutineが意図した動作にならないのが原因だとなんとなく分かった

**Comment by 25toma** [comment]
issue #39 のついでに終わらせました。
