### ISSUE TITLE
画面サイズに対する問題

### ISSUE THREAD

**Issue by 25toma** [at0x0ft/SRPG2018#90]
画面サイズは、standalone(1024x768)にしなければ、
Canvasシステム上画面崩壊などの問題が起こる。
そこで、今までその画面サイズにしていなかった場合に発生した問題を解決する。

現在確認している問題は、Floor情報表示ウィンドウが地図の左上を覆っていること。
それにより、プレイヤーが左上に行った場合、動作不能な状況に陥る。

**Comment by at0x0ft** [comment]
1600 * 900の画面サイズでビルドするよう設定できました.
それに伴ってウィンドウサイズ等々をbranch:41で調整しときました.
