### ISSUE TITLE
[bug] ノズルが表示された状態でFinishを押すとノズルが残ったままになる

### ISSUE THREAD

**Issue by kumachan-mis** [at0x0ft/SRPG2018#99]
ノズルが表示された状態でFinishを押すとノズルが残ったままになる. そのあと残ったノズルを適当に押すとさらに意図しない挙動を続ける.
* Attackを押すと攻撃は実行されるのにダメージバーはでない
* Chargeを押すと移動したあと強攻撃ができる
などを経験した.

**Comment by 25toma** [comment]
ノズルを消す処理を組み込んだので何とかなりました。
意図しない挙動を続けるのについては、意図しない入力の結果なので流石にどうしようもないです。
